### ISSUE TITLE
npm安装的版本有问题

### ISSUE THREAD

**Issue by WildDylan** [lisong/code-push-server#151]
1. 数据库里  版本 0.3.0，再 bin/www 中判断的却是 0.2.15
2. 修改上述判断之后，登录报错：

```
Executing (default): SELECT `id`, `username`, `password`, `email`, `identical`, `ack_code`, `created_at`, `updated_at` FROM `users` AS `Users` WHERE `Users`.`username` = 'admin' LIMIT 1;
[2018-08-21T17:52:41.609] [ERROR] cps:app - Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/jsonwebtoken/sign.js:101:20)
    at accountManager.login.then (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/routes/auth.js:49:16)
    at tryCatcher (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/node-v8.11.4-linux-x64/lib/node_modules/code-push-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by WildDylan** [comment]
好了解决了。
