### ISSUE TITLE
android下载的补丁包无法通过数据完整性检测

### ISSUE THREAD

**Issue by eternityBUG** [lisong/code-push-server#195]
### **描述**

app第一次更新可以成功，后面的更新全部无法通过完整性检测

这是将server部署在云服务上除了第一次更新下载的是源包，后面都是补丁包，这时候就无法通过数据完整性检测。
我在本地部署的时候测试，他不会下载补丁包，而是一直下载源包。源包是可以正常更新的。

![@{MBUNQ4M2}MT@YKP))LY_B](https://user-images.githubusercontent.com/30195529/58154899-41fc1b80-7ca5-11e9-81f3-d248b28c902b.png)

### **环境**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 23 other plugins)

System:

 (E:\android_sdk)ols : 25.2.5
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

### **插件**

```
code-push 2.0.6 "CodePushAcquisition"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
info.protonet.imageresizer 0.1.1 "Image Resizer"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
```

### **控制台**

`[CodePush] An update is available. {"appVersion":"0.0.1","deploymentKey":"4aWLIjIFmxKm3eZcQXMcTLzdU8gU4ksvOXqog","description":"测试本地55","downloadUrl":"https://xsapp.oss-cn-hangzhou.aliyuncs.com/storage/Ftd0Yl6IJpc9xYJH8xVrC6fKzrfB","isMandatory":false,"label":"v7","packageHash":"c0e9ebb431f51ab636a888d416a96e9855a54aa1392e89e4330acdd2dfdb57d9","packageSize":732544,"failedInstall":false}`

```
[CodePush] Package download success: {"deploymentKey":"4aWLIjIFmxKm3eZcQXMcTLzdU8gU4ksvOXqog","description":"测试本地55","label":"v7","appVersion":"0.0.1","isMandatory":false,"packageHash":"c0e9ebb431f51ab636a888d416a96e9855a54aa1392e89e4330acdd2dfdb57d9","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
main.js:1029 8
codePushUtil.js:36 [CodePush] Installing update
codePushUtil.js:36 [CodePush] Applying diff update
codePushUtil.js:36 [CodePush] Verifying hash for folder path: /codepush/deploy/versions/c0e9ebb431f51ab636a888d416a96e9855a54aa1392e89e4330acdd2dfdb57d9/
```
### **错误信息**

```
codePushUtil.js:41 [CodePush]  The update contents failed the data integrity check.. StackTrace: Error: The update contents failed the data integrity check.
    at packageHashSuccess (http://localhost/plugins/cordova-plugin-code-push/bin/www/localPackage.js:182:31)
    at Object.callbackFromNative (http://localhost/cordova.js:291:58)
    at <anonymous>:1:9
CodePushUtil.logError @ codePushUtil.js:41
CodePushUtil.invokeErrorCallback @ codePushUtil.js:45
installError @ localPackage.js:43
verificationFail @ localPackage.js:94
packageHashSuccess @ localPackage.js:182
callbackFromNative @ cordova.js:291
(anonymous) @ VM3586:1
codePushUtil.js:41 [CodePush] An error occurred during sync. The update contents failed the data integrity check.. StackTrace: Error: The update contents failed the data integrity check.
    at packageHashSuccess (http://localhost/plugins/cordova-plugin-code-push/bin/www/localPackage.js:182:31)
    at Object.callbackFromNative (http://localhost/cordova.js:291:58)
    at <anonymous>:1:9
CodePushUtil.logError @ codePushUtil.js:41
onError @ codePush.js:209
CodePushUtil.invokeErrorCallback @ codePushUtil.js:46
installError @ localPackage.js:43
verificationFail @ localPackage.js:94
packageHashSuccess @ localPackage.js:182
callbackFromNative @ cordova.js:291
(anonymous) @ VM3586:1
polyfills.js:2557 Uncaught Error: The update contents failed the data integrity check.
    at packageHashSuccess (localPackage.js:182)
    at Object.callbackFromNative (cordova.js:291)
    at <anonymous>:1:9
```

**Comment by eternityBUG** [comment]
解决了

**Comment by azhengyongqin** [comment]
@eternityBUG
### 请问下是如何解决的我也是这个问题，第一次能更新成功，后面的补丁包下载完了，更新就提示下面的错误！
```
"[CodePush] Applying diff update"
"[CodePush] Verifying hash for folder path: /codepush/deploy/versions/7c3c9f5c376e53dd379b0d289570a5ae1103cfb0232829161a5bdc6a20752a73/"
"[CodePush]  The update contents failed the data integrity check.. StackTrace: Error: The update contents failed the data integrity check.
```

**Comment by gaopeng1234567** [comment]
@eternityBUG  大佬可以说下怎么解决的么，我现在ios也遇见这个问题了。
