### ISSUE TITLE
更新资源找不到路径

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-server#20]
进入热更新 sdk 的逻辑下载失败  日志如下

```
2016-11-14 18:47:58.238 [info][tid:com.facebook.React.JavaScript] [CodePush] Error: 404: The specified resource does not exist.
RequestId:055a110c-0002-0139-0f64-3e17ec000000
```

---

我用 pm2 指定的 `process.yml` 信息如下

```
apps:
  - script : /Users/Jovi/work/mock/code-push-server/bin/www
    name   : code-push-server
    watch  : true
    env    :
      NODE_ENV: production
      PORT: 3000
      CONFIG_FILE: /Users/Jovi/work/mock/production/hotfix/config.js
```

---

对应的 `config.js` 如下

```
var config = {};
config.development = {
  //数据库配置
  db: {
    username: "jovi",
    password: "miaomiao",
    database: "codepush",
    host: "127.0.0.1",
    dialect: "mysql"
  },
  //七牛云存储配置 当storageType为qiniu时需要配置
  qiniu: {
    accessKey: "",
    secretKey: "",
    bucketName: "",
    downloadUrl: "" //文件下载域名地址
  },
  //文件存储在本地配置 当storageType为local时需要配置
  local: {
    storageDir: "/Users/jovi/work/mock/production/hotfix/workspaces/storage",
    //文件下载地址 CodePush Server 地址 + '/download' download对应app.js里面的地址
    downloadUrl: "http://localhost:3000/download"
  },
  common: {
    //登录jwt签名密钥，必须更改，否则有安全隐患，可以使用随机生成的字符串
    loginSecret: "CodePushServer",
    //当天登录密码错误尝试次数，超过次数帐户将会锁定。0:表示无限制，可能会出现暴力破解。 大于0:必须开启redis服务。
    tryLoginTimes: 0,
    //CodePush Web部署地址，也可以配置成CodePush Web地址
    //codePushWebUrl: "http://localhost:3001",
    //差异化更新版本生成数目 默认为3
    diffNums: 3,
    //数据目录，优化选项
    dataDir: "/Users/jovi/work/mock/production/hotfix/workspaces/data",
    //选择存储类型，目前支持local和qiniu配置
    storageType: "local"
  },
  //邮件配置，注册模块验证邮箱需要使用 参考https://github.com/nodemailer/nodemailer
  smtpConfig:{
    host: "smtp.mxhichina.com",
    port: 465,
    secure: true,
    auth: {
      user: "",
      pass: ""
    }
  },
  //配置redis, 注册时需要， 登录限制密码出错次数
  redis: {
    default: {
      host: "127.0.0.1",
      port: 6379,
      retry_strategy: function (options) {
        if (options.error.code === 'ECONNREFUSED') {
          // End reconnecting on a specific error and flush all commands with a individual error
          return new Error('The server refused the connection');
        }
        if (options.total_retry_time > 1000 * 60 * 60) {
            // End reconnecting after a specific timeout and flush all commands with a individual error
            return new Error('Retry time exhausted');
        }
        if (options.times_connected > 10) {
            // End reconnecting with built in error
            return undefined;
        }
        // reconnect after
        return Math.max(options.attempt * 100, 3000);
      }
    }
  }
}
config.production = Object.assign({}, config.development);
module.exports = config;
```

---

使用 code-push 推送资源成功后未发现报错  也确实看到了本地 `storage` 下存在了文件

![image](https://cloud.githubusercontent.com/assets/7262199/20262681/2b76f4ba-aa9e-11e6-871a-cd86b9e58398.png)

我用命令行和浏览器访问 `/download` 也发现了 404 的返回结果

看到了 `app.js` 的逻辑是 `app.use('/download', express.static(_.get(config, 'local.storageDir')))`

想问下问题出在哪里

感谢

**Comment by lisong** [comment]
直接访问 http://localhost:3000/download/+下载包名 呢？

**Comment by lisong** [comment]
react-native 项目的配置是？

**Comment by lisong** [comment]
```
http://127.0.0.1/updateCheck?deploymentKey=YourKey&appVersion=YourAppBinaryVersion&packageHash=&isCompanion=&label=&clientUniqueId=
```
返回值是？

**Comment by L-Jovi** [comment]
1. `http://localhost:3000/download/+下载包名` 指的是 `http://localhost:3000/download/FjEKlSkfRxPGs1YNo7PiW_drK8p0` 这样访问么  返回也是 `Not found`

2. RN 的配置指的是我的 `Info.plist` 文件嘛

我仅仅按照 `code-push` 文档指定了 `CodePushDeploymentKey` 的键值属性

3. 直接在浏览器访问下面的 api
```
http://127.0.0.1:3000/updateCheck?deploymentKey=XJiabUpIS6p7GIlSBLvdlwEDxEae4ksvOXqog&appVersion=0.2.2&packageHash=&isCompanion=&label=&clientUniqueId=
```

返回了我的热更新信息

```
{"updateInfo":{"downloadURL":"http://localhost:3000/download/Fv5JLn9fKmrJ4Mysnp6vEuj7_EB2","description":"\n    \n  本次更新\n    \n- 活跃维度下增加版本维度\n    \n- 横屏表格的日期控件报错\n    \n\n    \n  即将更新\n    \n- 图表支持点击查看数据\n    \n- 可查询日周月留存信息\n    \n","isAvailable":true,"isMandatory":true,"appVersion":"0.2.2","packageHash":"cb979a3e57ddbb5a84582bd5997d44c431e3f98fcd2681e54e31b4b5e6d9f7a9","label":"v1","packageSize":354064,"updateAppVersion":false,"shouldRunBinaryVersion":false}}
```

**Comment by lisong** [comment]
访问 `http://localhost:3000/download/Fv5JLn9fKmrJ4Mysnp6vEuj7_EB2` 这个地址呢？

**Comment by L-Jovi** [comment]
@lisong  感谢回复

在浏览器直接访问 `http://localhost:3000/download/Fv5JLn9fKmrJ4Mysnp6vEuj7_EB2` 也是 `Not Found`

**Comment by lisong** [comment]
终端有信息输出没？

**Comment by L-Jovi** [comment]
pm2 log 看了下实时的后台日志打印如下

```
0|code-pus | ::1 - - [14/Nov/2016:11:43:07 +0000] "GET /download/Fv5JLn9fKmrJ4Mysnp6vEuj7_EB2 HTTP/1.1" 404 10 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36"
0|code-pus | Error: Not Found
0|code-pus |     at /Users/jovi/work/mock/code-push-server/app.js:69:13
0|code-pus |     at Layer.handle [as handle_request] (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/layer.js:95:5)
0|code-pus |     at trim_prefix (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:312:13)
0|code-pus |     at /Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:280:7
0|code-pus |     at Function.process_params (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:330:12)
0|code-pus |     at next (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:271:10)
0|code-pus |     at /Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:618:15
0|code-pus |     at next (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:256:14)
0|code-pus |     at Function.handle (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:176:3)
0|code-pus |     at router (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:46:12)
0|code-pus |     at Layer.handle [as handle_request] (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/layer.js:95:5)
0|code-pus |     at trim_prefix (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:312:13)
0|code-pus |     at /Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:280:7
0|code-pus |     at Function.process_params (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:330:12)
0|code-pus |     at next (/Users/jovi/work/mock/code-push-server/node_modules/express/lib/router/index.js:271:10)
0|code-pus |     at SendStream.error (/Users/jovi/work/mock/code-push-server/node_modules/serve-static/index.js:121:7)
```

**Comment by lisong** [comment]
好奇怪，这个express中很简单的 app.use('/download', express.static(_.get(config, 'local.storageDir'))) 怎么找不到文件呢？
能不能在代码 app.use('/download', express.static(_.get(config, 'local.storageDir'))) 下面console.log(_.get(config, 'local.storageDir')); 然后看看目录是？

**Comment by lisong** [comment]
或者先 `pm2 restart process.yaml`

**Comment by L-Jovi** [comment]
很费解

我在 `app.js` 添加了 `console.log(_.get(config, 'local.storageDir'))` 之后用 pm2 重启了服务

然后浏览器访问 `http://localhost:3000/download/Fv5JLn9fKmrJ4Mysnp6vEuj7_EB2` 顺利下载到了文件

并且后台打印了路径 `0|code-pus | /Users/jovi/work/mock/production/hotfix/workspaces/storage`

然后我接着去 xcode 启动我的客户端项目  发现打印的日志仍旧是

```
2016-11-14 19:54:04.298 [info][tid:com.facebook.React.JavaScript] [CodePush] Error: 404: The specified resource does not exist.
RequestId:0b0d05ee-0002-006e-046d-3eb834000000
Time:2016-11-14T11:54:01.9837171Z
```

**Comment by lisong** [comment]
Info.plist 配置给我看看

**Comment by L-Jovi** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIcons</key>
	<dict/>
	<key>CFBundleIcons~ipad</key>
	<dict/>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.2.2</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>CodePushDeploymentKey</key>
	<string>XJiabUpIS6p7GIlSBLvdlwEDxEae4ksvOXqog</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSAppleMusicUsageDescription</key>
	<string>同意访问媒体库</string>
	<key>NSCalendarsUsageDescription</key>
	<string>同意访问日历</string>
	<key>NSCameraUsageDescription</key>
	<string>同意访问照相机</string>
	<key>NSContactsUsageDescription</key>
	<string>同意访问联系人</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>同意后台一直使用位置</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>同意定位</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>同意访问麦克风</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>同意访问媒体库</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UIStatusBarHidden</key>
	<true/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

```

**Comment by lisong** [comment]
```xml
<key>CodePushDeploymentKey</key>
<string>YourCodePushKey</string>
<key>CodePushServerURL</key>
<string>YourCodePushServerUrl</string>
```
指定`YourCodePushServerUrl` 地址为你的code-push-server 地址。要不然你的客户端不知道连接哪台机器下载文件

**Comment by L-Jovi** [comment]
@lisong  成功了  非常感谢！

**Comment by lisong** [comment]
如果配置到线上环境，`downloadURL`和`YourCodePushServerUrl ` 就需要用域名或者外网ip了，最好是用域名

**Comment by L-Jovi** [comment]
@lisong  收到!  感谢你一直不断耐心的回复和建议 :)

最后一个小问题  `config.js` 中的

`loginSecret: "CodePushServer"`

生产环境下建议的随机字符串多长最好呢   linux 下有木有推荐的生成工具

再次感谢

致意!

**Comment by lisong** [comment]
随机生成字符串 `openssl rand -base64 18`
还有`tryLoginTimes` 这个产生最好也配置一下，可以防止别人暴力破解密码

**Comment by L-Jovi** [comment]
@lisong  明白了  再次感谢
我会向同事们推荐你的这个项目  解决了这一时期的空白

致意
