### ISSUE TITLE
检查更新的时候，服务端报 404

### ISSUE THREAD

**Issue by maxrisk** [lisong/code-push-server#221]
```
[2019-08-23T18:17:25.584] [INFO] http - ::ffff:59.41.21.205 - - "GET /v0.1/public/codepush/update_check?deployment_key=xxxxxxx&app_version=0.1.0&package_hash=2126dc028d4fae0c078bd28e3ea7d0b1d49fc6ec870305387c4543332f989d30&client_unique_id=xxxxxx HTTP/1.1" 404 2434 "" "app/20190821-1 CFNetwork/978.0.7 Darwin/18.6.0"
^[[C[2019-08-23T18:19:01.723] [ERROR] cps:app - { NotFoundError: Not Found
    at /www/code-push-server/app.js:85:15
    at Layer.handle [as handle_request] (/www/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /www/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/www/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /www/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/www/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/www/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/www/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/www/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /www/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/www/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:127:14)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/www/code-push-server/node_modules/express/lib/router/route.js:131:14) message: 'Not Found', name: 'NotFoundError', status: 404 }
```

**Comment by lisong** [comment]
同 https://github.com/lisong/code-push-server/issues/220

**Comment by lingmingchang** [comment]
请问，这个问题你解决了么？
我把版本回退到5.6.0，但是大于5.6.0版本的APP收不到更新

**Comment by lisong** [comment]
最新release已经解决了

**Comment by nolan12345** [comment]
use "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git" instead "react-native-code-push": "x.x.x" in package.json
This approach solved my problem, other solutions didn't work

**Comment by YDJSZY** [comment]
一样的错。昨天刚拉的代码。docker成功跑起来了，但更新接口404

**Comment by gao520sun** [comment]
怎么解决的
