### ISSUE TITLE
code-push patch 执行出错

### ISSUE THREAD

**Issue by BaLaLaLs** [lisong/code-push-server#24]
code-push patch xbc-android Staging --des "asd"
-----------------------------------------
服务器
----------
PATCH /apps/xbc-android/deployments/Staging/release 404 33.010 ms - 1580
Error: Not Found
    at E:\code-push-server\app.js:71:13
    at Layer.handle [as handle_request] (E:\code-push-server\node_modules\expres
s\lib\router\layer.js:95:5)
    at trim_prefix (E:\code-push-server\node_modules\express\lib\router\index.js
:312:13)
    at E:\code-push-server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (E:\code-push-server\node_modules\express\lib\rou
ter\index.js:330:12)
    at next (E:\code-push-server\node_modules\express\lib\router\index.js:271:10
)
    at E:\code-push-server\node_modules\express\lib\router\index.js:618:15
    at next (E:\code-push-server\node_modules\express\lib\router\index.js:256:14
)
    at Function.handle (E:\code-push-server\node_modules\express\lib\router\inde
x.js:176:3)
    at router (E:\code-push-server\node_modules\express\lib\router\index.js:46:1
2)
    at Layer.handle [as handle_request] (E:\code-push-server\node_modules\expres
s\lib\router\layer.js:95:5)
    at trim_prefix (E:\code-push-server\node_modules\express\lib\router\index.js
:312:13)
    at E:\code-push-server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (E:\code-push-server\node_modules\express\lib\rou
ter\index.js:330:12)
    at next (E:\code-push-server\node_modules\express\lib\router\index.js:271:10
)
    at E:\code-push-server\node_modules\express\lib\router\index.js:618:15

**Comment by lisong** [comment]
这个方法好像没有实现

**Comment by kevinTutu** [comment]
假如热更新之后发现出错，我如何手动将其停止呢

**Comment by bobby4en** [comment]
请问解决了没有，我也出现这个异常

**Comment by martineden2017** [comment]
router.patch('/:appName/deployments/:deploymentName/release',
  middleware.checkToken, (req, res, next) => {
    return res.status(406).send('Not supported currently');
   ...
 }
修改更新这个功能很重要，怎么还没有完善啊？

**Comment by L-Jovi** [comment]
请问 `code-push patch` 目前实现了么 :)

**Comment by lisong** [comment]
v0.3.0已经支持

**Comment by raykle** [comment]
最新版使用 code-push patch 报错，`[Error]  Bad Request` 
发布更新和其他命令都没问题。请问要怎么解决呢？
