### ISSUE TITLE
when release a 100M file,server show error

### ISSUE THREAD

**Issue by leach-chen** [lisong/code-push-server#263]
when I use this command push a 100M file to the server

> code-push release-cordova TestCordovaCodePush android -m --description "android code push"

it show below error:

[2020-02-07T17:54:58.284] [INFO] http - ::ffff:192.168.0.102 - - "GET /download/fs/FsPCD2PkdSIMvtjp-p78CRYvgGFA HTTP/1.1" 200 42076 "" "undefined"
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat '/tmp/codepush_iHVmsB61jtRT3Cv7IRKPRHUF58LSdRsb/b3e088abbcd74bcbbfd00753d2f6a7cf411ce976785979f2d8d836ec31cb276d/dataCenter/CodePush/js/state/main_menu.js'
Emitted 'error' event on ZipFile instance at:
    at /home/leach/install/code-push-server/node_modules/yazl/index.js:30:26
    at FSReqCallback.oncomplete (fs.js:158:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/tmp/codepush_iHVmsB61jtRT3Cv7IRKPRHUF58LSdRsb/b3e088abbcd74bcbbfd00753d2f6a7cf411ce976785979f2d8d836ec31cb276d/dataCenter/CodePush/js/state/main_menu.js'
}

some one can help me?

**Comment by wang-weifeng** [comment]
我也遇到这样的错误，你解决了吗
