### ISSUE TITLE
code-push login登录报错

### ISSUE THREAD

**Issue by w11h22j33** [lisong/code-push-server#305]
通过NPM安装成功后，启动code-push-server。
使用code-push-cli（CLI v3.0.0）登录，输入token后报错，提示：
[Error]  Not Found

查看server日志，显示：
[2020-09-28T11:20:56.314] [ERROR] cps:app - { NotFoundError: Not Found
    at /usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/app.js:87:15
    at Layer.handle [as handle_request] (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:127:14)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/mpsp/node-v9.8.0-linux-x64/lib/node_modules/code-push-server/node_modules/express/lib/router/route.js:131:14) message: 'Not Found', name: 'NotFoundError', status: 404 }
[2020-09-28T11:20:56.314] [INFO] http - ::ffff:10.10.55.119 - - "GET /user HTTP/1.1" 404 3402 "" "undefined"

**Comment by JinYuSha0** [comment]
我也遇到了
看了一下code-push-cli在一个月前升级到了3.0.0
用回2.1.9的版本问题解决
`npm i code-push-cli@2.1.9 -g`
