### ISSUE TITLE
[android crash]安卓端在接收到版本更新之后, 杀掉进程重启App会崩溃一次

### ISSUE THREAD

**Issue by ChangerHe** [lisong/code-push-server#332]
react-native v0.64
react-native-code-push v7.0.2

IOS端目前没有测试, 安卓端每次发布新的热更新包之后, 重启app, app通过接口调用能够拿到最新的包. 但是再次重启app以应用更新的时候, app会崩溃一次, 错误日志如下:

com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/ANDROID_PACKAGE_NAME/files/CodePush/5f5fcb1234dbae2b8b24e615c657d6614483fc9d7f0daada03886f36d05c4ca0/CodePush/index.android.bundle: No such file or directory
	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(Unknown Source:2)
	at com.facebook.react.bridge.JSBundleLoader$2.loadScript(Unknown Source:6)
	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(Unknown Source:18)
	at com.facebook.react.p.q(Unknown Source:189)
	at com.facebook.react.p.c(Unknown Source:0)
	at com.facebook.react.p$e.run(Unknown Source:68)
	at java.lang.Thread.run(Thread.java:923)

**Comment by rocwind** [comment]
https://github.com/microsoft/react-native-code-push/issues/2148
用最新的react-native-code-push (7.0.4) 试试.

**Comment by xclidongbo** [comment]
解决了吗？遇到同样地问题了。 @ChangerHe
