### ISSUE TITLE
报错，找不到文件，请帮忙看看，谢谢了

### ISSUE THREAD

**Issue by juanq123** [lisong/code-push-server#40]
报找不到文件的错误
````
GET //download/Fqh9cD7XMY223d5g_SbncGC7FNh4 404 3.040 ms - 1907
Error: Not Found
    at /Users/jq/React-native/code-push-server/app.js:70:13
    at Layer.handle [as handle_request] (/Users/jq/React-native/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jq/React-native/code-p
   ush-server/node_modules/express/lib/router/index.js:312:13)
    at /Users/jq/React-native/code-push-server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/jq/React-native/code-push-server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/jq/React-native/code-push-server/node_modules/express/lib/router/index.js:271:10)
    at /Users/jq/React-native/code-push-server/node_modules/express/lib/router/index.js:618:15
    at next (/Users/jq/React-native/code-push-server/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/Users/jq/React-native/code-push-server/node_modules/express/lib/router/index.js:176:3)

````
我的config配置如下：
````
** local: {
    // Binary files storage dir, Do not use tmpdir and it's public download dir.
    storageDir: "/Users/jq/code-push-storage",
    // Binary files download host address which Code Push Server listen to. the files storage in storageDir.
    downloadUrl: "http://10.2.8.208:3000/download",
    // public static download spacename.
    public: '/download'
  },
  jwt: {
    // Recommended: 63 random alpha-numeric characters
    // Generate using: https://www.grc.com/passwords.htm
    tokenSecret: 'INSERT_RANDOM_TOKEN_KEY'
  },
  common: {
    /*
     * tryLoginTimes is control login error times to avoid force attack.
     * if value is 0, no limit for login auth, it may not safe for account. when it's a number, it means you can
     * try that times today. but it need config redis server.
     */
    tryLoginTimes: 0,
    // CodePush Web(https://github.com/lisong/code-push-web) login address.
    //codePushWebUrl: "http://localhost:3001/login",
    // create patch updates's number. default value is 3
    diffNums: 3,
    // data dir for caclulate diff files. it's optimization.
    dataDir: "/Users/jq/code-push-storage",
    // storageType which is your binary package files store. options value is ("local" | "qiniu" | "s3")
    storageType: "local",
    // options value is (true | false), when it's true, it will cache updateCheck results in redis.
    updateCheckCache: false
  },
````

**Comment by lisong** [comment]
`/Users/jq/code-push-storage`下是否有文件？

**Comment by juanq123** [comment]
有文件，已经解决了，谢谢，另外，version 可以是1.0，不一定是1.0.0 android ios 都可以是两位数的版本号

**Comment by juanq123** [comment]
不一定是三位的版本号

**Comment by juanq123** [comment]
code-push release wanna ./bundle/index.jsbundle 1.20.1 --mandatory true
看别人家的命令都是这样的，你家确是
code-push release-react CodePushDemo-ios iOS -d Production 
有什么区别吗

**Comment by lisong** [comment]
release-react更自动化些

**Comment by juanq123** [comment]
这个也是是code-push 插件饱含的命令是吧，不是你造出来的是吧

**Comment by juanq123** [comment]
一些实用上不知道，怎么用了，比如怎么回滚到上个版本等等，有没有相关的文章推荐啊

**Comment by stlemon** [comment]
@budingts 我的也是这个问题，请问是怎么解决的？

**Comment by ciuji** [comment]
@budingts 我的也有这个问题，请问是怎么解决的？
