### ISSUE TITLE
修改密码报错 Unexpected token '

### ISSUE THREAD

**Issue by LinqVicky** [lisong/code-push-server#81]
curl -X PATCH -H "Authorization: Bearer 0lvk9TBFVYimeopdohj9fZFCXOY34ksvOXqog" -H "Accept: application/json" -H "Content-Type:application/json" -d '{"oldPassword":"123456","newPassword":"654321"}' http://127.0.0.1:20040/users/password
--------------------------------------------------------------------
错误如下：
[2017-08-11 11:39:37.634] [ERROR] cps:app - { SyntaxError: Unexpected token '
    at parse (C:\Users\Administrator\AppData\Roaming\npm\node_modules\code-push-
server\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\code-push-server\
node_modules\body-parser\lib\read.js:116:18
    at invokeCallback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\c
ode-push-server\node_modules\raw-body\index.js:262:16)
    at done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\code-push-s
erver\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\code-push-server\node_modules\raw-body\index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  body: '\\'{oldPassword:123456,newPassword:654321}\\'',
  status: 400,
  statusCode: 400 }

**Comment by LinqVicky** [comment]
F:\ReactNativeCodeF>curl -X PATCH -H "Authorization: Bearer 40DGCxpz5HIKinzhSTOX
gXT5tRHb4ksvOXqog" -H "Accept: application/json" -H "Content-Type:application/js
on" -d {\\"oldPassword\\":\\"654321\\",\\"newPassword\\":\\"crm2017\\"} http://200.200.2
00.3:20040/users/password

{"status":"OK"}
-d 中将增加反斜线引号转义
